services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: atmosense-mosquitto
    restart: unless-stopped

    ports:
      - "127.0.0.1:1883:1883"

    volumes:
      - ./infrastructure/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data



  postgres:
      image: postgres:18.4-alpine
      container_name: atmosense-postgres
      restart: unless-stopped

      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      ports:
        - "127.0.0.1:5432:5432"

      volumes:
        - postgres_data:/var/lib/postgresql
        - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d:ro

      healthcheck:
        test:
          [
            "CMD-SHELL",
            "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
          ]
        interval: 5s
        timeout: 5s
        retries: 10


volumes:
  mosquitto_data:
  postgres_data:
