services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: atmosense-mosquitto
    restart: unless-stopped

    ports:
      - "127.0.0.1:1883:1883"

    volumes:
      - ./infrastructure/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data



  postgres:
      image: postgres:18.4-alpine
      container_name: atmosense-postgres
      restart: unless-stopped

      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      ports:
        - "127.0.0.1:5432:5432"

      volumes:
        - postgres_data:/var/lib/postgresql
        - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d:ro

      healthcheck:
        test:
          [
            "CMD-SHELL",
            "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
          ]
        interval: 5s
        timeout: 5s
        retries: 10


  grafana:
    image: grafana/grafana:13.1.0
    container_name: atmosense-grafana
    restart: unless-stopped

    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

    ports:
      - "127.0.0.1:3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      postgres:
        condition: service_healthy


  consumer:
    build: 
      context: ./application
      dockerfile: Dockerfile
    
    container_name: atmosense-consumer
    restart: unless-stopped

    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      MQTT_TOPIC: atmosense/device-F401RE/telemetry

      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      mosquitto: 
        condition: service_started
      postgres:
        condition: service_healthy








volumes:
  mosquitto_data:
  postgres_data:
  grafana_data:
